spin_manifest_version = 2

[application]
description = "A Booster 2024 clustering application"
name = "booster-2024-clustering"
version = "1.0.0"

[[trigger.http]]
route = "/cluster"
component = "cluster"

[component.cluster]
source = "./composed-http.wasm"
description = "A simple clustering component"

# Create a `[component.<name>]` section here for your component
