spin_manifest_version = 2

[application]
description = "A Booster 2024 clustering application"
name = "booster-2024-clustering"
version = "1.0.0"

[[trigger.http]]
# Setup the HTTP trigger to run on the `/cluster` endpoint

# Create a `[component.<name>]` section here for your component
